### ISSUE TITLE
Error fetching following profiles

### ISSUE THREAD

**Issue by SajjadKiani** [elizaOS/agent-twitter-client#35]
# Error fetching following profiles

i try to fetch fetch user followings using `scraper.fetchProfileFollowers()` bug get this error:

```
return new ApiError(response, data, `Response status: ${response.status}`);
           ^

ApiError: Response status: 404
    at ApiError.fromResponse (file:///home/saji/eye-ai-agent/node_modules/agent-twitter-client/dist/node/esm/index.mjs:35:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestApi (file:///home/saji/eye-ai-agent/node_modules/agent-twitter-client/dist/node/esm/index.mjs:109:12)
    at async getFollowersTimeline (file:///home/saji/eye-ai-agent/node_modules/agent-twitter-client/dist/node/esm/index.mjs:1516:15)
    at async fetchProfileFollowers (file:///home/saji/eye-ai-agent/node_modules/agent-twitter-client/dist/node/esm/index.mjs:1451:20)
    at async file:///home/saji/eye-ai-agent/index.js:23:23 {
  response: Response {
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 404,
      timingInfo: {
        startTime: 3259.312931,
        redirectStartTime: 0,
        redirectEndTime: 0,
        postRedirectStartTime: 3259.312931,
        finalServiceWorkerStartTime: 0,
        finalNetworkResponseStartTime: 3605.680247,
        finalNetworkRequestStartTime: 3259.636234,
        endTime: 3606.672621,
        encodedBodySize: 0,
        decodedBodySize: 0,
        finalConnectionTimingInfo: {
          domainLookupStartTime: 3259.312931,
          domainLookupEndTime: 3259.312931,
          connectionStartTime: 3259.312931,
          connectionEndTime: 3259.312931,
          secureConnectionStartTime: 3259.312931,
          ALPNNegotiatedProtocol: undefined
        }
      },
      cacheState: '',
      statusText: 'Not Found',
      headersList: HeadersList {
        cookies: null,
        [Symbol(headers map)]: Map(12) {
          'date' => { name: 'date', value: 'Tue, 31 Dec 2024 19:03:59 UTC' },
          'perf' => { name: 'perf', value: '7402827104' },
          'server' => { name: 'server', value: 'tsa_b' },
          'cache-control' => {
            name: 'cache-control',
            value: 'no-cache, no-store, max-age=0'
          },
          'content-length' => { name: 'content-length', value: '0' },
          'x-transaction-id' => { name: 'x-transaction-id', value: '1f44266d52e5649b' },
          'x-rate-limit-limit' => { name: 'x-rate-limit-limit', value: '50' },
          'x-rate-limit-reset' => { name: 'x-rate-limit-reset', value: '1735672739' },
          'x-rate-limit-remaining' => { name: 'x-rate-limit-remaining', value: '49' },
          'strict-transport-security' => {
            name: 'strict-transport-security',
            value: 'max-age=631138519'
          },
          'x-response-time' => { name: 'x-response-time', value: '5' },
          'x-connection-hash' => {
            name: 'x-connection-hash',
          }
        },
        [Symbol(headers map sorted)]: null
      },
      urlList: [ URL {} ],
      body: {
        stream: ReadableStream {
          [Symbol(kType)]: 'ReadableStream',
          [Symbol(kState)]: [Object: null prototype] {
            disturbed: true,
            reader: [ReadableStreamDefaultReader],
            state: 'closed',
            storedError: undefined,
            transfer: [Object: null prototype],
            controller: [ReadableByteStreamController]
          },
          [Symbol(nodejs.webstream.isClosedPromise)]: {
            promise: [Promise],
            resolve: [Function (anonymous)],
            reject: [Function (anonymous)]
          },
          [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function (anonymous)]
        },
        source: null,
        length: null
      }
    },
    [Symbol(headers)]: Headers {}
  },
  data: undefined
}

Node.js v20.17.0

```

**Comment by denizekiz** [comment]
make sure you are loggedin before calling function.


`import { Scraper} from 'agent-twitter-client';
const scraper = new Scraper();
await scraper.login('username','password',"email");
if (await scraper.isLoggedIn()) {
  console.log("Successfully logged in.");
} 
const followingResults = await scraper.fetchProfileFollowers('12345', 100);`

**Comment by trixiverse** [comment]
const loadCookies = () => {
    const load = fs.readFileSync("./cookies.json", "utf-8");
    const parsed = JSON.parse(load);
    return parsed.reduce((acc, current) => {
      const cookie = Cookie.fromJSON(current);
      acc.push(cookie);
      return acc;
    }, []);
  };

  const scraper = new Scraper();
  await scraper.setCookies(loadCookies());

  // const tweets = await scraper.getTweets('elonmusk', 10);
  // const tweetsAndReplies = scraper.getTweetsAndReplies('elonmusk');
  const latestTweet = await scraper.getLatestTweet('elonmusk');
  console.log({ latestTweet });

  const followers = scraper.getFollowers('StarverseX', 5);
  const following = scraper.getFollowing('StarverseX', 5);

  if (await scraper.isLoggedIn()) { console.log("Successfully logged in."); }
  const followingResults = await scraper.fetchProfileFollowers('elonmusk', 5);

above code gives error while trying to get the followingresults as below. while getlatesttweet worked fine.

 statusText: 'Bad Request',
      headersList: HeadersList {
        cookies: null,
        [Symbol(headers map)]: Map(15) {
          'date' => { name: 'date', value: 'Thu, 30 Jan 2025 18:43:28 GMT' },
          'perf' => { name: 'perf', value: '7402827104' },
          'server' => { name: 'server', value: 'tsa_b' },
          'content-type' => {
            name: 'content-type',
            value: 'application/json; charset=utf-8'
          },
          'cache-control' => {
            name: 'cache-control',
            value: 'no-cache, no-store, max-age=0'
          },
          'content-length' => { name: 'content-length', value: '204' },
          'content-encoding' => { name: 'content-encoding', value: 'gzip' },
          'x-transaction-id' => { name: 'x-transaction-id', value: '527a18eade2a5c90' },
          'x-rate-limit-limit' => { name: 'x-rate-limit-limit', value: '50' },
          'x-rate-limit-reset' => { name: 'x-rate-limit-reset', value: '1738263412' },
          'x-tfe-preserve-body' => { name: 'x-tfe-preserve-body', value: 'true' },
          'x-rate-limit-remaining' => { name: 'x-rate-limit-remaining', value: '48' },
          'strict-transport-security' => {
            name: 'strict-transport-security',
            value: 'max-age=631138519'
          },
          'x-response-time' => { name: 'x-response-time', value: '216' },
          'x-connection-hash' => {
            name: 'x-connection-hash',
            value: '3fb09a58fe89e9cf2296ff44befc5e6a5f4522cb9d2ae9914d0728ce5e8a6b72'
          }
        },
        [Symbol(headers map sorted)]: null
      },
      urlList: [
        https://twitter.com/i/api/graphql/rRXFSG5vR6drKr5M37YOTw/Followers?features=%7B%22android_graphql_skip_api_media_color_palette%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22creator_subscriptions_subscription_count_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Atrue%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_media_download_video_enabled%22%3Afalse%2C%22responsive_web_twitter_article_tweet_consumption_enabled%22%3Afalse%2C%22rweb_lists_timeline_redesign_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22subscriptions_verification_info_enabled%22%3Atrue%2C%22subscriptions_verification_info_reason_enabled%22%3Atrue%2C%22subscriptions_verification_info_verified_since_enabled%22%3Atrue%2C%22super_follow_badge_privacy_enabled%22%3Afalse%2C%22super_follow_exclusive_tweet_notifications_enabled%22%3Afalse%2C%22super_follow_tweet_api_enabled%22%3Afalse%2C%22super_follow_user_api_enabled%22%3Afalse%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Atrue%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22unified_cards_ad_metadata_container_dynamic_card_content_query_enabled%22%3Afalse%2C%22verified_phone_label_enabled%22%3Afalse%2C%22view_counts_everywhere_api_enabled%22%3Atrue%7D&variables=%7B%22count%22%3A5%2C%22includePromotedContent%22%3Afalse%2C%22userId%22%3A%22StarverseX%22%7D
      ],
      body: {
        stream: ReadableStream {
          [Symbol(kType)]: 'ReadableStream',
          [Symbol(kState)]: [Object: null prototype] {
            disturbed: true,
            reader: [ReadableStreamDefaultReader],
            state: 'closed',
            storedError: undefined,
            transfer: [Object: null prototype],
            controller: [ReadableByteStreamController]
          },
          [Symbol(nodejs.webstream.isClosedPromise)]: {
            promise: [Promise],
            resolve: [Function (anonymous)],
            reject: [Function (anonymous)]
          },
          [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function (anonymous)]
        },
        source: null,
        length: null
      }
    },
    [Symbol(headers)]: Headers {}
  },
  data: {
    errors: [
      {
        message: 'NumericString value expected. Received elonmusk',
        extensions: {
          name: 'MalformedVariablesError',
          source: 'Client',
          code: 366,
          kind: 'Validation',
          tracing: { trace_id: '527a18eade2a5c90' }
        },
        code: 366,
        kind: 'Validation',
        name: 'MalformedVariablesError',
        source: 'Client',
        tracing: { trace_id: '527a18eade2a5c90' }
      }
    ]
  }
}

Node.js v22.13.1
